// types.js

export const FETCH_SUBSCRIPTION_PLANS_SUCCESS = 'FETCH_SUBSCRIPTION_PLANS_SUCCESS';
export const SELECT_SUBSCRIPTION_PLAN = 'SELECT_SUBSCRIPTION_PLAN';
export const SET_SUBSCRIPTION_LENGTH = 'SET_SUBSCRIPTION_LENGTH';
export const SET_NUMBER_DEVICES = 'SET_NUMBER_DEVICES';
